generate:
  - types
  - client
accessModifier: package
namingStrategy: idiomatic
filter:
  operations:
    - apps/create-installation-access-token
    - issues/create
    - issues/get
    - projects/create-card
    - projects/delete-card
    - projects/list-cards
    - projects/move-card
    # Need to manually mark auto_merge.commit_title as nullable.
    # Also pull_request.merged.
    - pulls/get
    - pulls/list-files
    - pulls/list-reviews
    - pulls/update
    # Need to manually mark all schemas.repository date fields as accepting both string and number.
    # For example "pushed_at", "created_at", "updated_at".
    # Look at other "pushed_at" fields in other schemas.
    - repos/compare-commits
    - repos/create-release
    - repos/get-latest-release
    - repos/list-commits
    - repos/list-contributors
    - repos/list-pull-requests-associated-with-commit
    - repos/list-releases
    - repos/list-tags
  schemas:
    - installation-token
    # Need to manually mark label.description as nullable
    - label
    - simple-commit
    # Need to manually mark simple-installation.node_id as nullable
    - simple-installation
