generate:
  - types
  - client
accessModifier: package
namingStrategy: idiomatic
filter:
  operations:
    - apps/create-installation-access-token
    - issues/create
    - issues/get
    - projects/create-card
    - projects/delete-card
    - projects/list-cards
    - projects/move-card
    - pulls/get
    - pulls/list-files
    - pulls/list-reviews
    - pulls/update
    - repos/compare-commits
    - repos/create-release
    - repos/get-latest-release
    - repos/list-commits
    - repos/list-contributors
    - repos/list-pull-requests-associated-with-commit
    - repos/list-releases
    - repos/list-tags
  schemas:
    - installation-token
    - label
    - simple-commit
    - simple-installation
