generate:
  - types
  - client
accessModifier: package
namingStrategy: idiomatic
filter:
  tags:
    - repos
    - issues
    - pulls
    - projects
  schemas:
  - simple-commit
  - simple-installation
  - installation-token
