Description: CF Stack for the Penny Discord Bot

Parameters:
  apiGatewayName:
    Type: String
    Default: penny-bot-api
  FileNameAddCoins:
    Type: String
    Description: Filename of the code function for the adding of coins uploaded to S3
    Default: PennyLambdaAddCoins
  SponsorsFilename:
    Type: String
    Description: Filename containing the code to be executed when a new sponsor joins
    Default: SponsorLambda
  AutoPingsFilename:
    Type: String
    Description: Filename containing the code to be executed for auto-pings
    Default: AutoPingsLambda
  VPC:
    Description: VPC for the app
    Type: AWS::EC2::VPC::Id
    Default: vpc-08d1e66947d6200d6
  Subnet:
    Description: Subnet for the app
    Type: AWS::EC2::Subnet::Id
    Default: subnet-088d7192c6c67e077
  TaskDefinition:
    Description: Task def for the ECS task
    Type: String

Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties: 
      ClusterName: !Sub "${apiGatewayName}-Cluster"
  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Join ['-', [!Ref apiGatewayName, SecurityGroup]]
      VpcId: !Ref VPC
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['/', [/ecs, !Ref apiGatewayName]]
      RetentionInDays: 1
  Service:
    Type: AWS::ECS::Service
    Properties: 
      ServiceName: Penny-Bot
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinition
      DeploymentConfiguration:
        MinimumHealthyPercent: 100
        MaximumPercent: 200
      DesiredCount: 1
      LaunchType: FARGATE
      PlatformVersion: 1.4.0
      NetworkConfiguration: 
        AwsvpcConfiguration:
          # change to DISABLED if you're using private subnets that have access to a NAT gateway
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref Subnet
          SecurityGroups:
            - !Ref AppSecurityGroup

  apiGateway: 
    Type: AWS::ApiGatewayV2::Api
    Properties: 
      Name: !Ref apiGatewayName
      Description: API Endpoints for the discord Penny bot
      ProtocolType: HTTP
      #Target: 
        #- !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${FileNameAddCoins}-lambda/invocations
        #- !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${FileNameBot}-lambda/invocations

  apiGatewayStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref apiGateway
      StageName: prod
      AutoDeploy: true


  apiDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    Properties:
      ApiId: !Ref apiGateway
      StageName: !Ref apiGatewayStage

  # Coin lambda config

  addCoinIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      Description: Lambda Add Coin Integration
      ApiId: !Ref apiGateway
      ConnectionType: INTERNET 
      IntegrationMethod: POST
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt addCoinFunction.Arn
      PayloadFormatVersion: '2.0'

  addCoinRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref apiGateway
      RouteKey: 'POST /coin'
      Target: !Sub "integrations/${addCoinIntegration}"

  addCoinFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: penny-discord-bot
        S3Key: !Sub ${FileNameAddCoins}.zip
      FunctionName: !Sub ${FileNameAddCoins}-lambda
      Handler: handler 
      Role: !GetAtt lambdaIAMRole.Arn
      Runtime: provided.al2

  lambdaAddCoinPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Sub ${FileNameAddCoins}-lambda
      Principal: apigateway.amazonaws.com
    DependsOn: 
      - addCoinFunction
      
  # Sponsor lambda config
      
  sponsorsIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      Description: Lambda Sponsor Integration
      ApiId: !Ref apiGateway
      ConnectionType: INTERNET
      IntegrationMethod: POST
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt sponsorsFunction.Arn
      PayloadFormatVersion: '2.0'

  sponsorsRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref apiGateway
      RouteKey: "POST /sponsors"
      Target: !Sub "integrations/${sponsorsIntegration}"
      
  sponsorsFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: penny-discord-bot
        S3Key: !Sub ${SponsorsFilename}.zip
      FunctionName: !Sub ${SponsorsFilename}-lambda
      Handler: handler
      Role: !GetAtt lambdaIAMRole.Arn
      Runtime: provided.al2
    
  lambdaSponsorsPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Sub ${SponsorsFilename}-lambda
      Principal: apigateway.amazonaws.com
    DependsOn:
      - sponsorsFunction

  lambdaIAMRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow 
            Principal:
              Service: 
                - lambda.amazonaws.com
                - apigateway.amazonaws.com
      Policies: 
        - PolicyDocument: 
            Version: 2012-10-17
            Statement:
              - Action: 
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - lambda:InvokeFunction
                  - dynamodb:DescribeTable
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:BatchGetItem
                  - dynamodb:DeleteItem
                  - dynamodb:Attributes
                  - dynamodb:LeadingKeys
                  - dynamodb:ConditionCheckItem
                  - dynamodb:Scan
                  - lambda:UpdateFunctionCode
                  - secretsmanager:GetSecretValue
                Effect: Allow 
                Resource: 
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${FileNameAddCoins}-lambda:*
                  - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${FileNameAddCoins}-lambda
                  - !GetAtt dynamoUserTable.Arn
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/penny-bot-table/*
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${SponsorsFilename}-lambda:*
                  - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${SponsorsFilename}-lambda
                  - !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:prod/penny/penny-bot/discord-bot-token-VmhBXH
                  - !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:prod/penny/penny-bot/trigger-gh-readme-workflow-token-cpZwMv
          PolicyName: lamda
  
  lambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/PennyLambda
      RetentionInDays: 30
      
  # Auto-Pings lambda config
    
  autoPingsIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      Description: Lambda Auto-Pings Integration
      ApiId: !Ref apiGateway
      ConnectionType: INTERNET
      IntegrationMethod: POST
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt autoPingsFunction.Arn
      PayloadFormatVersion: '2.0'

  autoPingsRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref apiGateway
      RouteKey: 'POST /auto-pings'
      Target: !Sub "integrations/${autoPingsIntegration}"

  autoPingsRoute:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: penny-discord-bot
        S3Key: !Sub ${AutoPingsFilename}.zip
      FunctionName: !Sub ${AutoPingsFilename}-lambda
      Handler: handler
      Role: !GetAtt lambdaIAMRole.Arn
      Runtime: provided.al2

  lambdaAutoPingsRoutePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Sub ${AutoPingsFilename}-lambda
      Principal: apigateway.amazonaws.com
    DependsOn:
      - autoPingsFunction

  dynamoUserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "penny-bot-table"
      AttributeDefinitions:
        -
          AttributeName: "pk"
          AttributeType: "S"
        - 
          AttributeName: "sk"
          AttributeType: "S"
        -
          AttributeName: "data1"
          AttributeType: "S"
        -
          AttributeName: "data2"
          AttributeType: "S"
      KeySchema:
        - 
          AttributeName: "pk"
          KeyType: "HASH"
        - 
          AttributeName: "sk"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        -
          IndexName: "GSI-1"
          KeySchema:
            -
              AttributeName: "data1"
              KeyType: "HASH"
            -
              AttributeName: "pk"
              KeyType: "RANGE"
          Projection:
            ProjectionType: ALL
        -
          IndexName: "GSI-2"
          KeySchema:
            - 
              AttributeName: "data2"
              KeyType: "HASH"
            -
              AttributeName: "pk"
              KeyType: "RANGE"
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

Outputs:
  autoPingsLambdaArn:
    Value: !GetAtt autoPingsFunction.Arn

  sponsorsLambdaArn:
    Value: !GetAtt sponsorsFunction.Arn

  addCoinLambdaArn:
    Value: !GetAtt addCoinFunction.Arn

  dynamoDBArn:
    Value: !GetAtt dynamoUserTable.Arn

  


