name: Check cloudformation lint 

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Check cloudformation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup cloudformation lint
      uses: ScottBrenner/cfn-lint-action@v2.2.2
    - name: Run cloudformation lint on bot deployment stack
      run: cfn-lint -t Stack.yml
