name: Check CloudFormation lint 

on:
  push: { branches: [main] }
  pull_request:

jobs:
  lint:
    name: Check cloudFormation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup CloudFormation lint
      uses: ScottBrenner/cfn-lint-action@v2
    - name: Run CloudFormation lint on bot deployment stack
      run: cfn-lint -t Stack.yml
