name: Deploy the various lambda functions
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  push: { branches: [main] }

jobs:
  deploy-lambdas:
    strategy:
      matrix:
        target:
          - AutoPingsLambda
          - CoinsLambda
          - FaqsLambda
          - GHHooksLambda
          - SponsorsLambda
    uses: ./.github/workflows/deploy-lambda-by-target.yml
    with:
      target: ${{ matrix.target }}
    secrets: inherit
