name: test

on: 
  push:
    branches: 
      - "main"
  pull_request:
    branches: 
      - "*"

jobs:
  linux-all:
    strategy:
      fail-fast: false
      matrix:
        container:
          - swift:5.8-jammy
          - swiftlang/swift:nightly-main-jammy
    container: ${{ matrix.container }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out package
        uses: actions/checkout@v3
      - name: Run tests
        run: swift test --package-path ./CODE
